export const manufacturers = [
   "Acura",
   "Alfa Romeo",
   "Aston Martin",
   "Audi",
   "Bentley",
   "BMW",
   "Buick",
   "Cadillac",
   "Chevrolet",
   "Chrysler",
   "Citroen",
   "Dodge",
   "Ferrari",
   "Fiat",
   "Ford",
   "GMC",
   "Honda",
   "Hyundai",
   "Infiniti",
   "Jaguar",
   "Jeep",
   "Kia",
   "Lamborghini",
   "Land Rover",
   "Lexus",
   "Lincoln",
   "Maserati",
   "Mazda",
   "McLaren",
   "Mercedes-Benz",
   "MINI",
   "Mitsubishi",
   "Nissan",
   "Porsche",
   "Ram",
   "Rolls-Royce",
   "Subaru",
   "Tesla",
   "Toyota",
   "Volkswagen",
   "Volvo",
];

export const yearsOfProduction = [
   { title: "An", value: "" },
   { title: "2015", value: "2015" },
   { title: "2016", value: "2016" },
   { title: "2017", value: "2017" },
   { title: "2018", value: "2018" },
   { title: "2019", value: "2019" },
   { title: "2020", value: "2020" },
   { title: "2021", value: "2021" },
   { title: "2022", value: "2022" },
   { title: "2023", value: "2023" },
];

export const fuels = [
   {
      title: "Benzină",
      value: "Benzină",
   },
   {
      title: "Electricitate",
      value: "Electricitate",
   },
];

export const footerLinks = [
   {
      title: "Despre",
      links: [
         { title: "Cum funționează", url: "/despre" },
         { title: "Recomandate", url: "/despre" },
         { title: "Parteneriat", url: "/despre" },
         { title: "Relația de Afaceri", url: "/despre" },
      ],
   },
   {
      title: "Companie",
      links: [
         { title: "Evenimente", url: "/despre" },
         { title: "Blog", url: "/despre" },
         { title: "Podcast", url: "/despre" },
         { title: "Invită un prieten", url: "/despre" },
      ],
   },
   {
      title: "Rețele Sociale",
      links: [
         { title: "Discord", url: "/masini" },
         { title: "Instagram", url: "/masini" },
         { title: "Twitter", url: "/masini" },
         { title: "Facebook", url: "/masini" },
      ],
   },
];

export const locations = [
   "Bucharest",
   "Cluj-Napoca",
   "Timișoara",
   "Iași",
   "Constanța",
   "Craiova",
   "Brașov",
   "Galați",
   "Ploiești",
   "Oradea",
   "Brăila",
   "Arad",
   "Pitești",
   "Sibiu",
   "Bacău",
   "Târgu Mureș",
   "Baia Mare",
   "Buzău",
   "Botoșani",
   "Satu Mare",
];
